# Sistemas Lineares
## Uma revisão para o estudo de fluxo de potência em Sistemas Elétricos

### Definição de um sistema linear
Seja um sistema linear de $n$ variáveis e $m$ equações representado por:
\begin{equation}
\tag{1}
\begin{cases}
a_{11}x_1 + a_{12}x_2 + \dotsb + a_{1n}x_n = b_1 \\
a_{21}x_1 + a_{22}x_2 + \dotsb + a_{2n}x_n = b_2 \\
\qquad \vdots \\
a_{m1}x_1 + a_{m2}x_2 + \dotsb + a_{mn}x_n = b_m
\end{cases}
\end{equation}
Onde $x_j$ são as variáveis, $a_{ij}$ são os coeficientes e $b_{i}$ são as constantes.

Na forma matricial, estas variáveis, coeficientes e constantes podem ser representados por:
\begin{equation}
\tag{2}
Ax=B
\end{equation}
Onde $A$ é a matriz dos coeficientes, de dimensões $m$ por $n$, $x$ é o vetor das variáveis, de tamanho $n$, e $B$ é o vetor das constantes, de tamanho $m$, cujos elementos serão representados por:
\begin{equation}
\tag{3}
\begin{bmatrix}
a_{11} & a_{12} & \dotsb & a_{1n} \\
a_{21} & a_{22} & \dotsb & a_{2n} \\
\vdots & \vdots & \ddots & \vdots \\
a_{m1} & a_{m2} & \dotsb & a_{mn}
\end{bmatrix}
\begin{bmatrix}
x_{1} \\
x_{2} \\
\vdots \\
x_{n}
\end{bmatrix}
=
\begin{bmatrix}
b_{1} \\
b_{2} \\
\vdots \\
b_{m}
\end{bmatrix}
\end{equation}

Um sistema é dito triangular quando a quantidade de equações é igual à quantidade de variáveis, assim $m=n$.

### Solução matricial de sistemas lineares

Matricialmente, um sistema linear pode ser resolvido multiplicando a expressão:
\begin{equation}
\tag{2}
Ax=B
\end{equation}
pelo inverso da matriz $A$ pela esquerda:
\begin{equation}
\tag{4}
A^{-1}Ax=A^{-1}B
\end{equation}
Como:
\begin{equation}
\tag{5}
A^{-1}A = I
\end{equation}
e a matriz identidade é o elemento neutro da multiplicação, logo, o vetor das variáveis pode ser definido como:
\begin{equation}
\tag{6}
x=A^{-1}B
\end{equation}

### Solução iterativa de sistemas lineares pelo método de Jacobi (ou método de Gauss)

Para o sistema linear na forma vetorial $Ax=b$, este pode ser resolvido utilizando iterações de ponto fixo.

O método de Jacobi (ou Gauss) aplicado a um sistema de $n$ variáveis, consiste em isolar, na $i$-ésima equação, a variável $x_{i}$ e calcular o valor de sua $k$-ésima iteração utilizando os valores da $(k-1)$-ésima iteração das demais variáveis.

Considerando $x^{(1)}$ como o vetor com as aproximações iniciais das variáveis do sistema linear, a $i$-ésima equação tem como forma geral:

\begin{equation}
\tag{7}
x_{i}^{(k)}=\left(b_{i} - \sum_{j=1}^{j=i-1} a_{ij} x_j^{(k-1)} - \sum_{j=i+1}^{j=n} a_{ij} x_j^{(k-1)} \right) \cdot \left( a_{ii} \right)^{-1}
\end{equation}

Admite-se que a matriz $A$ é não-singular (inversível).

O método convergirá quando a norma infinita da diferença entre os resultados da $k$-ésima e da $(k-1)$-ésima iteração for menor que um valor de tolerância admitido. Ou seja, quando o maior valor dessa diferença tiver atingido a tolerância.

\begin{equation}
\tag{8}
\left\lVert x^{(k)} - x^{(k+1)} \right\rVert_\infty = \max_{i=1}^{i=n} \left| x_i^{(k)} - x_i^{(k+1)} \right|
\end{equation}

In [3]:
def gauss(A , b , x0 , tol , it_max):
    """
    Método de Jacobi/Gauss para solução de sistemas lineares de forma iterativa
    Entradas:
        A: matriz dos coeficientes (nxn)
        b: vetor das constantes (nx1)
        x0: vetor das aproximações iniciais das variáveis (nx1)
            no processo iterativo, este vetor armazenará os resultados da iteração anterior
        tol: tolerância esperada das soluções
        it_max: número máximo de iterações
    Saídas:
        x: vetor da solução do sistema dentro da tolerância estabelecida (nx1)
        it: número de iterações para chegar ao resultado de x
    Reproduzido de Justo et al (2020, p.123) com a adição de comentários para esclarecimentos didáticos futuros
    Referência bibliográfica:
    JUSTO, D. A. R. et al. Cálculo Numérico - Um Livro Colaborativo Versão Python. 19 de agosto de 2020. Disponível em: https://github.com/reamat/CalculoNumerico
    """
    # Garantindo que as matrizes/vetores do sistema sejam do tipo double
    A - A.astype("double")
    b = b.astype("double")
    x0 = x0.astype("double")

    ## TODO:
    # 1) Valores padrão para tol e it_max
    # 2) Garantir que A seja singular e triangular

    # Determina o número de variáveis pelo tamanho da matriz A
    n = np.shape(A)[0]
    # Cria um vetor de zeros para armazenar as soluções a cada iteração
    x = np.zeros((n,1))
    # Inicializa o contador de iterações
    it = 0

    # Laço principal para que o método não itere mais vezes do que o estabelecido
    while it < it_max:
        it += 1 # Contador de iterações
        for e in np.arange(n):
            # Inicializa o vetor das soluções com o valor da constante da linha atual
            x[e] = b[e]
            # Executa o somatório
            for i in np.concatenate((np.arange(0 , e) , np.arange(e+1 , n))):
                # Somatório de -A(i,j)*x0(j), onde x0(j) é o valor anterior
                x[e] -= A[e , i] * x0[i]
            # Depois do somatório, divide tudo por A(i,i)
            x[e] /= A[e , e]
        # Norma do máximo para determinar se a maior tolerância é menor que aquela escolhida
        if (np.linalg.norm(x - x0 , np.inf) < tol):
            # Se for, sai da função retornando o valor das variáveis (x) e o número de iterações (it)
            return x , it
        # Copia o resultado da iteração atual para que usar na próxima iteração como valor anterior
        x0 = np.copy(x)
    # Caso saia do laço por estourar o número de iterações, dá erro.
    raise NameError('O número máximo de iterações desejado foi excedido.')

### Solução iterativa de sistemas lineares pelo método de Gauss-Seidel

O método de Gauss-Seidel consiste em uma modificação no método de Jacobi para que, no cálculo da $i$-ésima equação na sua $k$-ésima iteração, sejam utilizandos os valores da iteral atual ($k$) e não da iteração anterior ($k-1$).

Assim, a forma geral para o método de Gauss-Seidel torna-se:

\begin{equation}
\tag{9}
x_{i}^{(k)}=\left(b_{i} - \textcolor{blue}{\sum_{j=1}^{j=i-1} a_{ij} x_j^{(k)}} - \sum_{j=i+1}^{j=n} a_{ij} x_j^{(k-1)} \right) \cdot \left( a_{ii} \right)^{-1}
\end{equation}

Admite-se que a matriz $A$ é não-singular (inversível).

A convergência deste método se dá da mesma forma que o método de Gauss.

In [4]:
def gaussseidel(A , b , x0 , tol , it_max):
    """
    Método de Gauss-Seidel para solução de sistemas lineares de forma iterativa
    Entradas:
        A: matriz dos coeficientes (nxn)
        b: vetor das constantes (nx1)
        x0: vetor das aproximações iniciais das variáveis (nx1)
            no processo iterativo, este vetor armazenará os resultados da iteração anterior
        tol: tolerância esperada das soluções
        it_max: número máximo de iterações
    Saídas:
        x: vetor da solução do sistema dentro da tolerância estabelecida (nx1)
        it: número de iterações para chegar ao resultado de x
    Reproduzido de Justo et al (2020, p.125) com a adição de comentários para esclarecimentos didáticos futuros
    Referência bibliográfica:
    JUSTO, D. A. R. et al. Cálculo Numérico - Um Livro Colaborativo Versão Python. 19 de agosto de 2020. Disponível em: https://github.com/reamat/CalculoNumerico
    """
    # Garantindo que as matrizes/vetores do sistema sejam do tipo double
    A - A.astype("double")
    b = b.astype("double")
    x0 = x0.astype("double")

    ## TODO:
    # 1) Valores padrão para tol e it_max
    # 2) Garantir que A seja singular e triangular

    # Determina o número de variáveis pelo tamanho da matriz A
    n = np.shape(A)[0]
    # Cria um vetor das soluções a cada iteração copiando o vetor dos resultados da iteração anterior
    x = np.copy(x0)
    # Inicializa o contador de iterações
    it = 0

    # Laço principal para que o método não itere mais vezes do que o estabelecido
    while it < it_max:
        it += 1 # Contador de iterações
        for e in np.arange(n):
            # Inicializa o vetor das soluções com o valor da constante da linha atual
            x[e] = b[e]
            # Executa o somatório
            for i in np.concatenate((np.arange(0 , e) , np.arange(e+1 , n))):
                # Somatório de -A(i,j)*x(j), onde x é o vetor dos resultados
                # Este vetor, na k-éstima iteração terá os elementos entre 0 e k-1 com resultado calculado na iteração atual
                # e os elementos entre k+1 e n com o resultado da iteração anterior
                x[e] -= A[e , i] * x[i]
            # Depois do somatório, divide tudo por A(i,i)
            x[e] /= A[e , e]
        # Norma do máximo para determinar se a maior tolerância é menor que aquela escolhida
        if (np.linalg.norm(x - x0 , np.inf) < tol):
            # Se for, sai da função retornando o valor das variáveis (x) e o número de iterações (it)
            return x , it
        # Copia o resultado da iteração atual para que usar na próxima iteração como valor anterior
        x0 = np.copy(x)
    # Caso saia do laço por estourar o número de iterações, dá erro.
    raise NameError('O número máximo de iterações desejado foi excedido.')

In [5]:
from __future__ import division
import numpy as np

A = np.array([[3 , 1 , -1] , [-1 , -4 , 1] , [1 , -2 , -5]])
b = np.array([[2] , [-10] , [10]])
x0 = np.array([[1] , [1] , [1]])
tol = 1e-5
it_max = 100

resultado = np.linalg.solve(A , b)
(resultado1 , it1) = gauss(A , b , x0 , tol , it_max)
(resultado2 , it2) = gaussseidel(A , b , x0 , tol , it_max)

print(f"Comparação dos métodos de resolução de sistemas lineares\n")
print(f"1) Usando a função numpy.linalg.solve (decomposição LU):")
print(resultado)
print(f"\n")
print(f"2) Usando o método de Gauss:")
print(f"número de iterações: {it1}")
print(resultado1)
print(f"\n")
print(f"3) Usando o método de Gauss-Seidel:")
print(f"número de iterações: {it2}")
print(resultado2)

Comparação dos métodos de resolução de sistemas lineares

1) Usando a função numpy.linalg.solve (decomposição LU):
[[-1.]
 [ 2.]
 [-3.]]


2) Usando o método de Gauss:
número de iterações: 12
[[-0.99999671]
 [ 1.99999954]
 [-2.99999738]]


3) Usando o método de Gauss-Seidel:
número de iterações: 8
[[-1.00000149]
 [ 1.99999987]
 [-3.00000025]]
